spring:
  datasource:
    url: jdbc:postgresql://${TASK_MANAGEMENT_DB_HOST}:${TASK_MANAGEMENT_DB_PORT}/${TASK_MANAGEMENT_DB_NAME}?currentSchema=${TASK_MANAGEMENT_DB_SCHEMA}
    username: ${TASK_MANAGEMENT_DB_USERNAME}
    password: ${TASK_MANAGEMENT_DB_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    default-schema: ${TASK_MANAGEMENT_DB_SCHEMA}
    liquibase-schema: ${TASK_MANAGEMENT_DB_SCHEMA}
    enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_schema: ${TASK_MANAGEMENT_DB_SCHEMA}
    hibernate:
      ddl-auto: update
    open-in-view: